services:
  database:
    image: postgres:14
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data  # Mapea la carpeta 'pgdata' en la raíz del proyecto